apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shard-ratelimit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shard-ratelimit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "shard-ratelimit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shard-ratelimit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shard-ratelimit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{end}}
          lifecycle:
            preStop:
              exec:
                command: ["sleep",{{.Values.preStopSeconds|quote}}]
          command:
            - "/bin/ratelimit"
            {{if .Values.useStaticReplicas }}
            - -r={{.Values.replicaCount}}
            {{end}}
            - -n={{ .Release.Namespace }}
            - -s={{ include "shard-ratelimit.fullname" . }}
            - -c={{.Values.configmap}}
            - -l={{.Values.log}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{.Values.port}}
              protocol: TCP
            - name: http
              containerPort: {{.Values.httpPort}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /check_health
              port: http
          readinessProbe:
            httpGet:
              path: /check_health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
