apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "shard-ratelimit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shard-ratelimit.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints","services","configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "shard-ratelimit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shard-ratelimit.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shard-ratelimit.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "shard-ratelimit.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io