apiVersion: v1
kind: Service
metadata:
  name: {{ include "shard-ratelimit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shard-ratelimit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "shard-ratelimit.selectorLabels" . | nindent 4 }}
